#!/usr/bin/python

import subprocess
import os
import time

connected = "Connected"
attempts = 0
max_attempts = 10

while attempts < max_attempts:
    status = subprocess.getoutput("mullvad status | grep -io Connected")
    print(status)
    if status == connected:
        time.sleep(1)
        os.system("qbittorrent &")
        exit()
    else:
        time.sleep(1)
        attempts += 1
        print(attempts)
