#!/bin/sh
#
# hyprland startup applications
#

killall "rslsync"
rslsync

killall "dunst"
dunst &

killall ""
foot --server &

killall "waybar"
waybar &

sleep 1
pgrep -x qbittorrent || $HOME/.config/hypr/scripts/qbittorrent &
