#!/bin/sh
#
# hyprland startup applications
#

killall "flameshot"
flameshot &

killall "syncthing"
syncthing >> ~/.local/syncthing &

killall "dunst"
dunst &

killall ""
foot --server &

killall "waybar"
waybar &

sleep 1
pgrep -x qbittorrent > /dev/null || $HOME/.config/hypr/scripts/qbittorrent &
